### ISSUE TITLE
plugin does not support worlds with mixed-case names

### ISSUE THREAD

**Issue by IBCodin** [bergerkiller/MyWorlds#1]
Note: I'm running a Linux server and as such the file/folder names "BigTown" and "bigtown" do NOT refer to the same file.

I was trying to install and use MyWorlds as it had several features that my current multi-world manager does not that I was interested in experimenting with.

When it first loaded I asked it to list the 'worlds' and it displayed my list of worlds (including the mixed-case names) along with a 'loaded' or 'not loaded' status. 

I used the `/load world` command to load the additional worlds that were in my 'former' manager.
There were no errors reported.

Upon shutting down the server and later restarting it, the worlds did not load. 
It is my recollection that 'world not found' errors were in the log, but I no-longer have the log.

I shutdown the server and went and reviewed the worlds.yml file.
It contained all of the worlds, but the section names (that matched my world names) were all lower case.
It was interesting to note that the spawn location (inside the section) had the correct case for the name.

While I appreciate a case-insensitive search as much as the next person, the 'actual' case of the name needs to be preserved.

I suspect the problem lies in WorldConfig where it changes incoming names to lower case before searching for them.
If it doesn't find one that matches, it uses the lower case name to create one.

If you would like, I'll fork the repo and work on it and submit a pull request.

**Comment by bergerkiller** [comment]
Ah I see, is it true that Linux's file system is case-sensitive? In Windows (which I use) you can simply check if a file exists, and it is not case-sensitive, it is likely that this causes the 'is this a world' check to fail.

EDIT

Yup it is...ok I'll fetch some code there so it will always use the case-sensitive coding in the configuration.

EDIT

Fixed it in 1.27, closing it. If it still persists don't hesitate to write a new ticket.
